name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
    branches-ignore:
      - 'dependabot/**'
  pull_request:

permissions:
  contents: read

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Create tests execution report for all test projects
      run: ./test-projects.sh test createTestsExecutionReport
    - name: Check reports were created
      run: ./test-projects.sh checkReports
    - name: Create HTML report for regression tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: createRegressionHtmlReport
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
      working-directory: src/visual-regression
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: src/visual-regression
    - name: Run Playwright tests with Percy
      run: npx percy exec -- npx playwright test
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      working-directory: src/visual-regression

  build-on-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build -i
    - name: Create tests execution report for all test projects
      run: ./test-projects.ps1 test createTestsExecutionReport
    - name: Check reports were created
      run: ./test-projects.ps1 checkReports
    - name: Create HTML report for regression tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: createRegressionHtmlReport
