name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:

permissions:
  contents: read

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef
      with:
        arguments: build
    - name: Create tests execution report for all test projects
      run: ./test-projects.sh test createTestsExecutionReport
    - name: Check reports were created
      uses: andstor/file-existence-action@v1
      with:
        allow_failure: true
        files: "
         test-projects/junit5-single-module/build/reports/tests-execution/html/test.html,
         test-projects/junit5-single-module/build/reports/tests-execution/json/test.json, 
         test-projects/junit5-single-module/build/reports/tests-execution/mermaid/test.txt,
         test-projects/kotest-single-module/build/reports/tests-execution/html/test.html,
         test-projects/kotest-single-module/build/reports/tests-execution/json/test.json, 
         test-projects/kotest-single-module/build/reports/tests-execution/mermaid/test.txt,
         test-projects/spock-multi-module/build/reports/tests-execution/html/test.html,
         test-projects/spock-multi-module/build/reports/tests-execution/json/test.json, 
         test-projects/spock-multi-module/build/reports/tests-execution/mermaid/test.txt,
         test-projects/spock-multi-module/module1/build/reports/tests-execution/html/test.html,
         test-projects/spock-multi-module/module1/build/reports/tests-execution/json/test.json, 
         test-projects/spock-multi-module/module1/build/reports/tests-execution/mermaid/test.txt,
         test-projects/spock-multi-module/module2/build/reports/tests-execution/html/test.html,
         test-projects/spock-multi-module/module2/build/reports/tests-execution/json/test.json, 
         test-projects/spock-multi-module/module2/build/reports/tests-execution/mermaid/test.txt,
         test-projects/spock-multiple-test-tasks/build/reports/tests-execution/html/integrationTest.html,
         test-projects/spock-multiple-test-tasks/build/reports/tests-execution/json/integrationTest.json, 
         test-projects/spock-multiple-test-tasks/build/reports/tests-execution/mermaid/integrationTest.txt,
         test-projects/spock-single-module/build/reports/tests-execution/html/test.html,
         test-projects/spock-single-module/build/reports/tests-execution/json/test.json, 
         test-projects/spock-single-module/build/reports/tests-execution/mermaid/test.txt,
         test-projects/testNG-single-module/build/reports/tests-execution/html/test.html,
         test-projects/testNG-single-module/build/reports/tests-execution/json/test.json,
         test-projects/testNG-single-module/build/reports/tests-execution/mermaid/test.txt
         "
  build-on-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef
      with:
        arguments: build -i
    - name: Create tests execution report for all test projects
      run: ./test-projects.ps1 test createTestsExecutionReport
    - name: Check reports were created
      uses: andstor/file-existence-action@v1
      with:
        allow_failure: true
        files: "
         test-projects/junit5-single-module/build/reports/tests-execution/html/test.html,
         test-projects/junit5-single-module/build/reports/tests-execution/json/test.json, 
         test-projects/junit5-single-module/build/reports/tests-execution/mermaid/test.txt,
         test-projects/kotest-single-module/build/reports/tests-execution/html/test.html,
         test-projects/kotest-single-module/build/reports/tests-execution/json/test.json, 
         test-projects/kotest-single-module/build/reports/tests-execution/mermaid/test.txt,
         test-projects/spock-multi-module/build/reports/tests-execution/html/test.html,
         test-projects/spock-multi-module/build/reports/tests-execution/json/test.json, 
         test-projects/spock-multi-module/build/reports/tests-execution/mermaid/test.txt,
         test-projects/spock-multi-module/module1/build/reports/tests-execution/html/test.html,
         test-projects/spock-multi-module/module1/build/reports/tests-execution/json/test.json, 
         test-projects/spock-multi-module/module1/build/reports/tests-execution/mermaid/test.txt,
         test-projects/spock-multi-module/module2/build/reports/tests-execution/html/test.html,
         test-projects/spock-multi-module/module2/build/reports/tests-execution/json/test.json, 
         test-projects/spock-multi-module/module2/build/reports/tests-execution/mermaid/test.txt,
         test-projects/spock-multiple-test-tasks/build/reports/tests-execution/html/integrationTest.html,
         test-projects/spock-multiple-test-tasks/build/reports/tests-execution/json/integrationTest.json, 
         test-projects/spock-multiple-test-tasks/build/reports/tests-execution/mermaid/integrationTest.txt,
         test-projects/spock-single-module/build/reports/tests-execution/html/test.html,
         test-projects/spock-single-module/build/reports/tests-execution/json/test.json, 
         test-projects/spock-single-module/build/reports/tests-execution/mermaid/test.txt,
         test-projects/testNG-single-module/build/reports/tests-execution/html/test.html,
         test-projects/testNG-single-module/build/reports/tests-execution/json/test.json,
         test-projects/testNG-single-module/build/reports/tests-execution/mermaid/test.txt
         "
