name: Execute Wrapper Upgrade

on:
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  upgrade_wrapper:
    name: Execution
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git configuration
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git config --global url."https://unused-username:${TOKEN}@github.com/".insteadOf "https://github.com/"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Upgrade Wrappers
        run: ./gradlew clean upgradeGradleWrapperAll --continue -Porg.gradle.java.installations.auto-download=false
        env:
          WRAPPER_UPGRADE_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
